### ISSUE TITLE
Support an upside-down (chronological) view and UI organisation

### ISSUE THREAD

**Issue by arri-cc** [continuousit/seq-releases#103]
We have a few utility apps that execute a series of commands and scripts, so we end up with a mixture of structured and unstructured log data, mostly single line entries.  While I'm able to target the logs via both enriched properties and api key properties, I find it difficult reviewing the sequence of events in reverse chronological order.  So for certain scenarios it would be great to have the option to control the order used to display the events.  If this feature is already there, I wasn't able to find it in the docs, and I didn't try to guess at it.

**Comment by nblumhardt** [comment]
Hi Arri - I've moved this to our UserVoice site since I don't expect to tackle it in the immediate future - still a worthwhile improvement for us though. Do you find you're still in as much need for this feature?

http://seq.uservoice.com/forums/268188-general/suggestions/8952592-support-an-upside-down-chronological-layout

**Comment by arri-cc** [comment]
Sounds good.  It would still be nice to have, but I just worked around it using the API and viewing in another tool we wrote.
