### ISSUE TITLE
Add the possibility to run the SEQ server UI over HTTPS

### ISSUE THREAD

**Issue by vinicola** [continuousit/seq-releases#263]
When logging in to the SEQ server, login credentials are sent as plain text over HTTP. It would be desirable to have at least the login page to post the credentials over HTTPS.  

If  possible, maybe an option to disable HTTP-access altogether would be a nice to have feature.

**Comment by nblumhardt** [comment]
Hi, and thanks for dropping by!

Seq fully supports HTTPS - once enabled, all logins etc. will be via HTTPS and HTTP/plain text is disabled completely.

You can find some more details here:

https://getseq.atlassian.net/wiki/display/SEQ10/Configure+SSL

After making this change you do need to update logger configuration to point to an HTTPS URL instead of the old HTTP one, so good to plan ahead here.

Does this help?

**Comment by vinicola** [comment]
Yes, that's exactly what I was looking for. Too bad my search foo didn't yield the desired result earlier, but still good the feature is already there.

Thanks for the quick reply and keep up the great work with Seq!
