### ISSUE TITLE
Bulk import log files

### ISSUE THREAD

**Issue by Jaben** [continuousit/seq-releases#278]
I'm not saying this would be hard to develop a little tool to do this, but it might be nice to have a simple method inside Seq to bulk import log file(s).

Use case: Apps. For example, Papercut generates JSON log files the the users email them to me, etc. I'd love to be able to import them and tag them with arbitrary properties (e.g. Issue: "1234", User: "JoeG"). Much nicer than having to scan them in Sublime Text.

Thanks Nick.

**Comment by nblumhardt** [comment]
Thanks for the suggestion Jaben. I'd really like to get this one turned around, especially since the Serilog sink for Seq already partially implements this.

I'm not going to be able to move it forward in the immediate future though, so moved to UserVoice here: http://seq.uservoice.com/forums/268188-general/suggestions/8952373-log-file-import-tool

Cheers!

**Comment by nblumhardt** [comment]
Hi @Jaben, just a heads-up - https://github.com/datalust/seq-import and https://github.com/nblumhardt/serilog-sinks-json should have you covered! Any and all feedback welcome.

**Comment by Jaben** [comment]
Ohh, exactly what I'm after! Kick ass. Thanks Nick!

**Comment by slimflem** [comment]
Thanks Nick, immediately useful.
