### ISSUE TITLE
Seq won't open in IE Edge / Sparten

### ISSUE THREAD

**Issue by johnkattenhorn** [continuousit/seq-releases#300]
Just a Head's Up really, I'm loving Seq v2.0 but I thought I'd let you know it opens fine with IE in Windows 2010 Build 10130 but no dice in Sparten; get the following

    Hmm, we can't reach this page
    Make sure you've got the right URL : http://localhost:5341

**Comment by nblumhardt** [comment]
Thanks for letting us know, we'll check this out!

**Comment by nblumhardt** [comment]
It looks like Spartan will refuse to open all `localhost` URLs; I'd hope this is fixed in a near-future update, but either way this isn't something we can have any impact on unfortunately:

http://answers.microsoft.com/en-us/insider/forum/insider_internet-insider_spartan/spartan-will-not-view-localhost-sites/92a0a2f0-f1ba-4ab9-a486-7fe1fa1f5b97

Cheers!
